### ISSUE TITLE
handle function missing

### ISSUE THREAD

**Issue by christophemassin** [arrilot/laravel-data-anonymization#1]
Hello, 

After migrating from laravel 5.4 to 5.6, i got an error in the annonymisation script. 

-  Method Arrilot\LaravelDataAnonymization\Commands\DbAnonymizeCommand::handle() does not exist  

to solve it, you just have to add this to the DbAnonymizeCommand. 

```
    public function handle()
    {
    	return $this->fire();
    }
```

**Comment by arrilot** [comment]
Thx, fixed
