### ISSUE TITLE
Small mistakes, big help

### ISSUE THREAD

**Issue by bertalanimre** [arrilot/laravel-data-anonymization#11]
Hello Ilya,

Just want to tell you, I've experienced some small "bugs" working with your anonymizer and I would strongly recommend fixing these. No big deal, just annoying stuff. Like:
* After `make:anonymizer` in the newly created file the Faker is not being used, thus I have to copy-paste it every time to the front to use it `use Faker\Generator as Faker;`
* Again, after `make:anonymizer` the file created is called `App\WhateverAnonymizer.php`. On Linux, this is a huge problem, since the folder structure is different and I have to rename all the files by removing the `App\` from each of them. 
* I don't know if you can do something about it, but doing a `composer update` after creating a new class feels terrible. Especially because I have to manage about 40 other packages and hard-lock them not to update. If you can do anything about this and make a command like `refresh:anonymizer` to reload the classes, that would be more than great.

They are no big deal and I can get around them always, it is just a heads up to make your work even better and easier to use on Linux. :) Thank you again for Your work!

**Comment by arrilot** [comment]
Hello, all those issues should be resolved for now in new Major release https://github.com/arrilot/laravel-data-anonymization/releases/tag/2.0.0

Feel free to upgrade if you are on L8 already
