### ISSUE TITLE
Any way to anonymize only where not NULL ?

### ISSUE THREAD

**Issue by bertalanimre** [arrilot/laravel-data-anonymization#12]
I was wondering:
Is there a way to tell your script to anonymize only the database entries where is a value already present and it is not NULL ?
I'm trying to make it work, but it seems no matter what I do it get's done on every record.

**Comment by arrilot** [comment]
Here is the syntax, I've just checked it with my database.
```
      $this->table('users', function (Blueprint $table) {
            $table->column('name')->where('name IS NOT NULL')->replaceWith('John');
        });
```
