### ISSUE TITLE
Users and emails in sync

### ISSUE THREAD

**Issue by bertalanimre** [arrilot/laravel-data-anonymization#15]
Hello again!

I'm back with another issue I'm facing. I wish to anonymize users but as usual, their email and name are completely different. Is there a way to make them relevant to each other?

**Bad Example:**

- Name: John Doe
- Email: clark.nobody@example.com

**Good Example:**

- Name John Doe
- Email: doe@example.com | john@example.com | johndoe@example.com | john.doe@example.com | doe.john@example.com... etc

Relevant question for addresses. Like the ZIP code and the city should match (I don't care for the street names tho)

And another thing, one user has multiple email columns (email,sub_email,news_email). How can I make then all the same?

**Comment by arrilot** [comment]
I'm afraid it's not possible at the moment 
There is no way to pass data between different columns

All "replace" options are listed there https://github.com/arrilot/data-anonymization/blob/master/README.md

**Comment by bertalanimre** [comment]
:( Sad. Very sad.... This sounded logical tho
