### ISSUE TITLE
Different locale ?

### ISSUE THREAD

**Issue by bertalanimre** [arrilot/laravel-data-anonymization#7]
I know Faker is able to use different locale if we tell him, but somehow seemingly doesn't work with this project. Is it included and if yes, how to change the locale that I wish to make example data for?

**Comment by arrilot** [comment]
Hi, I've released a fix for that. Anonymizer now uses Faker from the service container. You can set locale for that Faker in config/app.php -> faker_locale

Could you please update to the latest version 1.1.3 and check if everything is fine.

**Comment by bertalanimre** [comment]
Works like a charm! Thank you for the fast response and sorry for not replying fast enough. :) Also, I recommend updating your README with the new info. 

Added:
```
/*
    |--------------------------------------------------------------------------
    | Locale settings for Laravel Data Anonymization
    |--------------------------------------------------------------------------
    |
    | Here you may configure the locale settings for your application. Out of
    | the box, Laravel Data Anonymization uses English as default language.
    | This can be changed to many of the supported languages by Faker listed
    | on the following URL: https://github.com/fzaninotto/Faker/tree/master/src/Faker/Provider
    |
    | Example settings: 'faker_locale' => ('hu_HU'),
    |
    */

    'faker_locale' => ('hu_HU'),
```
