### ISSUE TITLE
Missing class?

### ISSUE THREAD

**Issue by bertalanimre** [arrilot/laravel-data-anonymization#8]
After executing `php artisan make:anonymizer HuntingCompanyAnonymizer` I have a new file as `database/anonymization/App\HuntingCompanyAnonymizer.php`. This is almost OK, that `App\` is not required, it makes Linux directory structures look stupid. So I modify the file name simply to `database/anonymization/HuntingCompanyAnonymizer.php`. I modify it as the following:
```
<?php

use Arrilot\DataAnonymization\Blueprint;
use Arrilot\LaravelDataAnonymization\AbstractAnonymizer;
use Faker\Generator as Faker;

class HuntingCompanyAnonymizer extends AbstractAnonymizer
{
    /**
     * Run the database anonymization.
     *
     * @return void
     */
    public function run()
    {
        $this->table('hunting_companies', function (Blueprint $table) {

            $table->column('name')->replaceWith(function(Faker $faker) {
                return $faker->unique()->company;
            });
        });
    }
}
```
So I had to add the faker manually, that should be default.

After this, I add `$this->call(HuntingCompanyAnonymizer::class);` to the `DatabaseAnonymizer.php`. I though I'm ready to go, but now when I execute `php artisan db:anonymize` I get the following error:
```
me@localhost ~/sites/project-anon $ php artisan db:anonymize
Anonymized: UserTableAnonymizer

In AbstractAnonymizer.php line 93:
                                              
  Class 'HuntingCompanyAnonymizer' not found  
                                              
```
Any workaround or fix coming lately or I'm just stupid and doesn't know how to use it? :D

**Comment by bertalanimre** [comment]
Interestingly, I've done another `php artisan anonymization:install` without removing anything and now it works. WTH? :D

**Comment by arrilot** [comment]
Hi. you need to add database/anonymization to composer.json -> autoload -> classmap (just added it to docs) and do composer dump-autoload if you manually move files in this dir.
